### ISSUE TITLE
tracepath: command not found

### ISSUE THREAD

**Issue by v1s1t0r1sh3r3** [xtonousou/shIP#26]
## Expected Behavior

Not sure, never saw it working. :smile:

## Current Behavior

An error happens sometimes. tracepath: command not found and for google dns 8.8.8.8 it says destination is unrecheable but I have internet connection and I can ping to 8.8.8.8 without problems. It seems tracepath error happens depending of the host.

## Screenshots (if appropriate):
Sorry, the screenshot is in spanish.
![error](https://s30.postimg.org/vik85lgk1/ship2.png)

## Steps to Reproduce (for bugs)

1. cd /to/your/ship/path
2. ./ship.sh -r somewhere.net
3.
4.

## Context

I'm trying to see the route to host

## Your Environment

* Script's version used: 2.0
* Linux Distribution (e.g. Arch, Gentoo, Ubuntu): Kali 2016.2
* Link to your project (if appropriate):

**Comment by xtonousou** [comment]
As for the **destination is unreachable**, the timeout is very short. I will create two 'timeout' variables, one short and one long. The *short timeout* will be used for `wget` commands and the *long timeout* will be used to check internet connection. For the `tracepath: command not found`, I will probably bring `traceroute` and `mtr` to the field. A function will be added to check which tool is installed and an appropriate stream edit for each case scenario. I will close the issue, when it's fixed. Thank you!

**Comment by v1s1t0r1sh3r3** [comment]
nice to hear that!

**Comment by xtonousou** [comment]
@v1s1t0r1sh3r3 last update should have fixed the problem.
Could you please test and report back?
Thanks!

**Comment by v1s1t0r1sh3r3** [comment]
I downloaded ship from dev branch and tested again.

![img](https://s28.postimg.org/kwaeegu7h/Captura.png)

Everything works except the `ship.sh -r 8.8.8.8`. It starts to check but something happens.

**Comment by xtonousou** [comment]
@v1s1t0r1sh3r3 now it should be ok.

**Comment by v1s1t0r1sh3r3** [comment]
yeah, now is working!!!

**Comment by xtonousou** [comment]
I'm glad to hear that!
